plugins {
    id 'com.android.application'
}

dependencies {
    // Library lainnya...
    implementation "androidx.documentfile:documentfile:1.0.1"
}

android {
    namespace 'com.example.obbinstaller'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.obbinstaller'
        minSdk 33
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}
